apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cloudflare-ddns.fullname" . }}
  labels:
    {{- include "cloudflare-ddns.labels" . | nindent 4 }}
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "cloudflare-ddns.selectorLabels" . | nindent 8 }}
        spec:
          containers:
            - name: cloudflare-ddns
              image: timothyjmiller/cloudflare-ddns
              env:
                - name: CF_API_EMAIL
                  value: "{{ .Values.cloudflareDDNS.cfAPIEmail }}"
                - name: CF_API_KEY
                  value: "{{ .Values.cloudflareDDNS.cfAPIKey }}"
                - name: CF_DDNS_HOSTNAME
                  value: "{{ .Values.cloudflareDDNS.cfDDNSHostname }}"
                - name: CF_ZONE_NAME
                  value: "{{ .Values.cloudflareDDNS.cfZoneName }}"
                - name: CF_DDNS_ENABLED
                  value: "{{ .Values.cloudflareDDNS.cfDDNSEnabled }}"